In [31]:
import pandas as pd
import seaborn as sns
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 16, 8

from scipy.stats import norm
from scipy import stats

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from numpy import array
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict




import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score

# Data + Preprocessing

In [3]:
my_dataset = pd.read_csv('synthetic.csv')

In [4]:
my_dataset.head(10)

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815      170136.00       160296.36   
1     1   PAYMENT   1864.28  C1666544295       21249.00        19384.72   
2     1  TRANSFER    181.00  C1305486145         181.00            0.00   
3     1  CASH_OUT    181.00   C840083671         181.00            0.00   
4     1   PAYMENT  11668.14  C2048537720       41554.00        29885.86   
5     1   PAYMENT   7817.71    C90045638       53860.00        46042.29   
6     1   PAYMENT   7107.77   C154988899      183195.00       176087.23   
7     1   PAYMENT   7861.64  C1912850431      176087.23       168225.59   
8     1   PAYMENT   4024.36  C1265012928        2671.00            0.00   
9     1     DEBIT   5337.77   C712410124       41720.00        36382.23   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0            0.00        0               0  
1  M2044282225             0.0            0.00        0               0  
2   C553264065             0.0            0.00        1               0  
3    C38997010         21182.0            0.00        1               0  
4  M1230701703             0.0            0.00        0               0  
5   M573487274             0.0            0.00        0               0  
6   M408069119             0.0            0.00        0               0  
7   M633326333             0.0            0.00        0               0  
8  M1176932104             0.0            0.00        0               0  
9   C195600860         41898.0        40348.79        0               0

In [5]:
#my_dataset.replace({0: 1, 1: 0})

In [6]:
my_dataset.head(10)

step      type    amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
0     1   PAYMENT   9839.64  C1231006815      170136.00       160296.36   
1     1   PAYMENT   1864.28  C1666544295       21249.00        19384.72   
2     1  TRANSFER    181.00  C1305486145         181.00            0.00   
3     1  CASH_OUT    181.00   C840083671         181.00            0.00   
4     1   PAYMENT  11668.14  C2048537720       41554.00        29885.86   
5     1   PAYMENT   7817.71    C90045638       53860.00        46042.29   
6     1   PAYMENT   7107.77   C154988899      183195.00       176087.23   
7     1   PAYMENT   7861.64  C1912850431      176087.23       168225.59   
8     1   PAYMENT   4024.36  C1265012928        2671.00            0.00   
9     1     DEBIT   5337.77   C712410124       41720.00        36382.23   

      nameDest  oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0  M1979787155             0.0            0.00        0               0  
1  M2044282225             0.0            0.00        0               0  
2   C553264065             0.0            0.00        1               0  
3    C38997010         21182.0            0.00        1               0  
4  M1230701703             0.0            0.00        0               0  
5   M573487274             0.0            0.00        0               0  
6   M408069119             0.0            0.00        0               0  
7   M633326333             0.0            0.00        0               0  
8  M1176932104             0.0            0.00        0               0  
9   C195600860         41898.0        40348.79        0               0

In [7]:
x_1000=my_dataset[my_dataset['isFraud']==1]
x_1000=x_1000.head(1000)
y_1000=my_dataset[my_dataset['isFraud']==0]
y_1000=y_1000.head(1000)
frames = [x_1000,y_1000]
setA = pd.concat(frames)
numerical = ['type','amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']

In [8]:
pd.get_dummies(setA['type'], prefix='type')

dfA = pd.concat([setA,pd.get_dummies(setA['type'], prefix='type')],axis=1)

dfA.drop(['type'],axis=1, inplace=True)
dfA.drop(['step'],axis=1, inplace=True)
dfA.drop(['nameOrig'],axis=1, inplace=True)
dfA.drop(['nameDest'],axis=1, inplace=True)

amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  newbalanceDest  \
2      181.0          181.0             0.0             0.0             0.0   
3      181.0          181.0             0.0         21182.0             0.0   
251   2806.0         2806.0             0.0             0.0             0.0   
252   2806.0         2806.0             0.0         26202.0             0.0   
680  20128.0        20128.0             0.0             0.0             0.0   

     isFraud  isFlaggedFraud  type_CASH_IN  type_CASH_OUT  type_DEBIT  \
2          1               0             0              0           0   
3          1               0             0              1           0   
251        1               0             0              0           0   
252        1               0             0              1           0   
680        1               0             0              0           0   

     type_PAYMENT  type_TRANSFER  
2               0              1  
3               0              0  
251             0              1  
252             0              0  
680             0              1

In [9]:
x_500000=my_dataset[my_dataset['isFraud']==1]
x_500000=x_500000.head(500000)
y_500000=my_dataset[my_dataset['isFraud']==0]
y_500000=y_500000.head(500000)
frames = [x_500000,y_500000]
setB = pd.concat(frames)
numerical = ['type','amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']

In [10]:
pd.get_dummies(setB['type'], prefix='type')

dfB = pd.concat([setB,pd.get_dummies(setB['type'], prefix='type')],axis=1)

dfB.drop(['type'],axis=1, inplace=True)
dfB.drop(['step'],axis=1, inplace=True)
dfB.drop(['nameOrig'],axis=1, inplace=True)
dfB.drop(['nameDest'],axis=1, inplace=True)



amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  newbalanceDest  \
2      181.0          181.0             0.0             0.0             0.0   
3      181.0          181.0             0.0         21182.0             0.0   
251   2806.0         2806.0             0.0             0.0             0.0   
252   2806.0         2806.0             0.0         26202.0             0.0   
680  20128.0        20128.0             0.0             0.0             0.0   

     isFraud  isFlaggedFraud  type_CASH_IN  type_CASH_OUT  type_DEBIT  \
2          1               0             0              0           0   
3          1               0             0              1           0   
251        1               0             0              0           0   
252        1               0             0              1           0   
680        1               0             0              0           0   

     type_PAYMENT  type_TRANSFER  
2               0              1  
3               0              0  
251             0              1  
252             0              0  
680             0              1

In [11]:
x_646=my_dataset[my_dataset['isFraud']==1]
x_646=x_646.head(646)
y_500000=my_dataset[my_dataset['isFraud']==0]
y_500000=y_500000.head(500000)
frames = [x_646,y_500000]
setC = pd.concat(frames)
numerical = ['type','amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']

In [12]:
pd.get_dummies(setC['type'], prefix='type')

dfC = pd.concat([setC,pd.get_dummies(setC['type'], prefix='type')],axis=1)

dfC.drop(['type'],axis=1, inplace=True)
dfC.drop(['step'],axis=1, inplace=True)
dfC.drop(['nameOrig'],axis=1, inplace=True)
dfC.drop(['nameDest'],axis=1, inplace=True)

amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  newbalanceDest  \
2      181.0          181.0             0.0             0.0             0.0   
3      181.0          181.0             0.0         21182.0             0.0   
251   2806.0         2806.0             0.0             0.0             0.0   
252   2806.0         2806.0             0.0         26202.0             0.0   
680  20128.0        20128.0             0.0             0.0             0.0   

     isFraud  isFlaggedFraud  type_CASH_IN  type_CASH_OUT  type_DEBIT  \
2          1               0             0              0           0   
3          1               0             0              1           0   
251        1               0             0              0           0   
252        1               0             0              1           0   
680        1               0             0              0           0   

     type_PAYMENT  type_TRANSFER  
2               0              1  
3               0              0  
251             0              1  
252             0              0  
680             0              1

In [14]:
features = ['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'type_CASH_IN', 'type_CASH_OUT', 'type_DEBIT', 'type_PAYMENT', 'type_TRANSFER']
X = dfA[features]
y = dfA['isFraud']

It is possible to switch between the three different subsets in the cell above. 
To work with subset A use:
    #X = dfA[features]
    #y = dfA['isFraud']
To work with any other subset, change the A in the example in to the letter of the demanded subset.


In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state =1)

In [18]:
pd.DataFrame(X).fillna(0)

amount  oldbalanceOrg  newbalanceOrig  oldbalanceDest  \
2          181.00         181.00            0.00            0.00   
3          181.00         181.00            0.00        21182.00   
251       2806.00        2806.00            0.00            0.00   
252       2806.00        2806.00            0.00        26202.00   
680      20128.00       20128.00            0.00            0.00   
...           ...            ...             ...             ...   
500228   95332.00     4973570.68      5068902.68       196493.05   
500229   54013.84     5068902.68      5122916.52       632826.38   
500230  235563.13     5122916.52      5358479.65      2050184.60   
500231  204958.72     5358479.65      5563438.37      3203816.74   
500232  161830.57     5563438.37      5725268.94      1764435.41   

        newbalanceDest  type_CASH_IN  type_CASH_OUT  type_DEBIT  type_PAYMENT  \
2                 0.00             0              0           0             0   
3                 0.00             0              1           0             0   
251               0.00             0              0           0             0   
252               0.00             0              1           0             0   
680               0.00             0              0           0             0   
...                ...           ...            ...         ...           ...   
500228       101161.05             1              0           0             0   
500229       578812.53             1              0           0             0   
500230      1970263.62             1              0           0             0   
500231      2998858.02             1              0           0             0   
500232      1602604.84             1              0           0             0   

        type_TRANSFER  
2                   1  
3                   0  
251                 1  
252                 0  
680                 1  
...               ...  
500228              0  
500229              0  
500230              0  
500231              0  
500232              0  

[508213 rows x 10 columns]

In [19]:
np.where(np.isnan)

(array([0]),)

# Performance

## k-NN

In [35]:
knn = KNeighborsClassifier()
knn_scores = cross_val_score(knn, X_train,y_train, cv=10, scoring='precision')
print(knn_scores)
knn.fit(X_train, y_train)

[0.8322884  0.84493671 0.87397709 0.84713376 0.85828025 0.86111111
 0.85393258 0.87163233 0.85646688 0.86427457]


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [36]:
predictions1 = knn.predict(X_test)

In [22]:
score1 = knn.score(X_test, y_test)
print(score1)

0.9949037316883602


In [37]:
cm1 = metrics.confusion_matrix(y_test, predictions1)
print(cm1)

[[99774   222]
 [  296  1351]]


In [38]:
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions1))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     99996
           1       0.86      0.82      0.84      1647

    accuracy                           0.99    101643
   macro avg       0.93      0.91      0.92    101643
weighted avg       0.99      0.99      0.99    101643



## DT

In [46]:
dt = DecisionTreeClassifier()
dt_scores = cross_val_score(dt, X_train,y_train, cv=10, scoring='precision')
print(dt_scores)
dt.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [47]:
predictions2 = dt.predict(X_test)

In [48]:
score1 = dt.score(X_test, y_test)
print(score1)

0.9986029534744153


In [49]:
cm2 = metrics.confusion_matrix(y_test, predictions2)
print(cm2)

[[99918    78]
 [   64  1583]]


In [50]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     99996
           1       0.95      0.96      0.96      1647

    accuracy                           1.00    101643
   macro avg       0.98      0.98      0.98    101643
weighted avg       1.00      1.00      1.00    101643



## MLP

In [51]:
mlp = MLPClassifier()
mlp_scores = cross_val_score(mlp, X_train,y_train, cv=10, scoring='precision')
print(mlp_scores)
mlp.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [52]:
predictions3 = mlp.predict(X_test)

In [53]:
score1 = mlp.score(X_test, y_test)
print(score1)

0.9838650964650788


In [54]:
cm3 = metrics.confusion_matrix(y_test, predictions3)
print(cm3)

[[99996     0]
 [ 1640     7]]


In [55]:
from sklearn.metrics import classification_report

print(classification_report(y_test, predictions3))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     99996
           1       1.00      0.00      0.01      1647

    accuracy                           0.98    101643
   macro avg       0.99      0.50      0.50    101643
weighted avg       0.98      0.98      0.98    101643

